### ISSUE TITLE
Solutions filled in in main branch?

### ISSUE THREAD

**Issue by LNKeat** [learn-co-curriculum/phase-3-hashketball#1]
### Canvas Link

https://learning.flatironschool.com/courses/4323/assignments/133686?module_item_id=277356

### Concern

I cloned the main branch and it seems it already has all the solutions filled in.

**Comment by lizbur10** [comment]
Hi @LNKeat ! Thanks for bringing this to our attention - the solution has been removed from the starter code. 💙
