### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by betalantz** [learn-co-curriculum/phase-3-hashketball#2]
### Canvas Link

https://learning.flatironschool.com/courses/4543/assignments/157659

### Concern

There is a typo which could be confusing.

### Suggested Changes

In _Building Methods_ section, the text "we can chain [] calls the hash it returns." should read "we can chain [] calls **on** the hash it returns."

**Comment by lizbur10** [comment]
Thanks @betalantz  - this has been fixed 💙
